import React,{useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {getStaff,addStaff,getAttendance,saveAttendance,getAdvances,addAdvance,getLeaves,addLeave} from '../api/attendance';
const today=()=>new Date().toISOString().slice(0,10);
export default function Attendance(){const qc=useQueryClient(),[tab,setTab]=useState('attendance'),[date,setDate]=useState(today()),[staff,setStaff]=useState({name:'',mobile:''}),[advance,setAdvance]=useState({staff_id:'',amount:'',advance_date:today(),notes:''}),[leave,setLeave]=useState({staff_id:'',from_date:today(),to_date:today(),reason:''});
 const staffQ=useQuery({queryKey:['staff'],queryFn:getStaff}),att=useQuery({queryKey:['attendance',date],queryFn:()=>getAttendance(date)}),adv=useQuery({queryKey:['advances'],queryFn:getAdvances}),leaves=useQuery({queryKey:['leaves'],queryFn:getLeaves}); const refresh=()=>{qc.invalidateQueries({queryKey:['staff']});qc.invalidateQueries({queryKey:['attendance']});qc.invalidateQueries({queryKey:['advances']});qc.invalidateQueries({queryKey:['leaves']})}; const mutate=(fn,data)=>fn(data).then(refresh).catch(e=>alert(e.response?.data?.error||e.message));
 return <div className="page-container"><div className="page-header"><h1>Attendance Manager</h1></div><div className="tabs"><button className={`tab-btn ${tab==='attendance'?'active':''}`} onClick={()=>setTab('attendance')}>Attendance</button><button className={`tab-btn ${tab==='staff'?'active':''}`} onClick={()=>setTab('staff')}>Staff</button><button className={`tab-btn ${tab==='advance'?'active':''}`} onClick={()=>setTab('advance')}>Advances</button><button className={`tab-btn ${tab==='leave'?'active':''}`} onClick={()=>setTab('leave')}>Leaves</button></div>
 {tab==='attendance'&&<div className="card"><div className="card-body"><label>Date <input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><table className="table"><thead><tr><th>Staff</th><th>Status</th><th>Note / leave reason</th></tr></thead><tbody>{(att.data||[]).map(s=><tr key={s.id}><td>{s.name}</td><td><select value={s.status||'present'} onChange={e=>mutate(saveAttendance,{staff_id:s.id,date,status:e.target.value,notes:s.notes})}>{['present','absent','half','leave'].map(x=><option key={x}>{x}</option>)}</select></td><td><input defaultValue={s.notes||''} onBlur={e=>mutate(saveAttendance,{staff_id:s.id,date,status:s.status||'present',notes:e.target.value})}/></td></tr>)}</tbody></table></div></div>}
 {tab==='staff'&&<div className="card"><div className="card-body"><form onSubmit={e=>{e.preventDefault();mutate(addStaff,staff);setStaff({name:'',mobile:''})}}><input required placeholder="Staff name" value={staff.name} onChange={e=>setStaff({...staff,name:e.target.value})}/><input placeholder="Mobile" value={staff.mobile} onChange={e=>setStaff({...staff,mobile:e.target.value})}/><button className="btn btn-primary">Add staff</button></form><table className="table"><tbody>{(staffQ.data||[]).map(s=><tr key={s.id}><td>{s.name}</td><td>{s.mobile}</td></tr>)}</tbody></table></div></div>}
 {tab==='advance'&&<div className="card"><div className="card-body"><form onSubmit={e=>{e.preventDefault();mutate(addAdvance,advance)}}><select required value={advance.staff_id} onChange={e=>setAdvance({...advance,staff_id:e.target.value})}><option value="">Staff</option>{(staffQ.data||[]).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input required type="number" placeholder="Advance amount" value={advance.amount} onChange={e=>setAdvance({...advance,amount:e.target.value})}/><input type="date" value={advance.advance_date} onChange={e=>setAdvance({...advance,advance_date:e.target.value})}/><button className="btn btn-primary">Record advance</button></form><table className="table"><thead><tr><th>Staff</th><th>Date</th><th>Amount</th></tr></thead><tbody>{(adv.data||[]).map(a=><tr key={a.id}><td>{a.staff_name}</td><td>{a.advance_date?.slice(0,10)}</td><td>₹{a.amount}</td></tr>)}</tbody></table></div></div>}
 {tab==='leave'&&<div className="card"><div className="card-body"><form onSubmit={e=>{e.preventDefault();mutate(addLeave,leave)}}><select required value={leave.staff_id} onChange={e=>setLeave({...leave,staff_id:e.target.value})}><option value="">Staff</option>{(staffQ.data||[]).map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><input type="date" value={leave.from_date} onChange={e=>setLeave({...leave,from_date:e.target.value})}/><input type="date" value={leave.to_date} onChange={e=>setLeave({...leave,to_date:e.target.value})}/><input required placeholder="Leave reason" value={leave.reason} onChange={e=>setLeave({...leave,reason:e.target.value})}/><button className="btn btn-primary">Record leave</button></form><table className="table"><thead><tr><th>Staff</th><th>Dates</th><th>Reason</th></tr></thead><tbody>{(leaves.data||[]).map(l=><tr key={l.id}><td>{l.staff_name}</td><td>{l.from_date?.slice(0,10)} – {l.to_date?.slice(0,10)}</td><td>{l.reason}</td></tr>)}</tbody></table></div></div>}</div>}
